language: node_js

node_js:
  - node
  - lts/boron
  - lts/argon

before_script:
  - yarn compile

before_deploy:
  - yarn pack --filename package.tgz

deploy:
  - provider: npm
    email: contact@florentin-dubois.fr
    api_key:
      secure: QF1kc/q6i/8ffhAZIBBi579U5fRpcGWFVXsjeSKMJJolTuSR9gdGbPG60r1nJhW/IZRSwec93DpA9vF1n0GhYv/dy9O16LCw22+i9ZoDPC6TFcCosdPfQQARTQ//R5H07QfObwkqe+bcLrPhTM1h7vIah6i0gd/cXsJqr0MH49rMMyRlkaLcJ5ZCUg0q44qJgF0gbCACTKP4kRp7yW4HDs5CHEouzUVlP46JdHi6O2LBERwrcOb1U+VH/aweOFo4RDcB36K3ecjo/ZmQwZSbN6N6l6pbCjve63tzc1XOHmW9Yv5SfYxWA6mLdDkHf1sLCCiFfMadSMCrKUBIEY3UNE3kCCDMjKdLm5IlLlMX2Tw9oN+5055V2WyqOLZtzgHdc5iBnXXWk4183MB6vw8Sb3zMf6Cpki4U6oCvGBoDyTlmhqUzs1fOF86MG75NAOWFFPURexruFrTuQQOBfLzwnjbzLx5AZHNE7uD7Od8DefNjtS9Tt7K4YNvU7I8xMmTqRgF7OENqj+BFpOD+w64DZrOHIB4TUD2JZWfzdXVQuXXqzcQPmvW1JAeafwtg5k5YzBZYDCVZ+OFToo7CCs1lP3mvdmhvlM2e7hThCLOQ4Udl92kzDZMRxOQEzK5j8lVU7y5FgJU6HOffJYWWpkX/kb9BUeOXnWpmI/uBmaxTg6Y=

    skip_cleanup: true
    file: package.tgz
    on:
      repo: starry-comet/comet-ioc
      tags: true

  - provider: releases
    api_key:
      secure: N/bEH6SYwA3GDw76qlOLsh6VrQIaOx5bFcQa8FECdlJ/79GEDIH/NJwAlOnyU/z/nUoYTWXUSmtTkdGC1dZV6NUtZHeVrxECSSZhJ2XevDUueKiiIZIqbzl2zeogZoX2NVg3T81f8HysT/2oP9Xb3KBGZiMKj5rsqe4fSL5OrgL2lRXRzhLGtKYKinmrS83tTR14aSq8YktTbz3gTMPtoxdu9MCubKsZB+AZJruOaItXg4KX/4tNcBINJdDYZH2x+vrG219upaOCG8G6Fze35Ni3U/9d6+JPzvW7Ovf1pQlDLH/1E+NNrlXW9a4V4YK86Arb6VoEvIePq9tN8PoEPyqB0s0RyEBncjWqJ4RApkOIDwMxkuOlV3KZynHCI8G5DQwXSX//zfaNOKPefYvYUI/yHiM4dfsfAb3nvMsctyoSxRshyaB6mFYu44gjy3gLrhKJpKjdZQXg5SiLE/fNyE9gRvwOA9znpTtCm6E4lHn97t4Ozc1Z/8YkRWHEbFBKYOEpJJuT6NfyHK6BPoIRrZ6PkiiZGrQKzPXFiJYVJpUEPHa8DkW9xxcZwfNStQcQETjV0Vf4A7AC/lq8yLvvRgDCygob+Ws97z6WhWGTmFw+ip6dNB2ACJ9HhLj8KIfQ0MW2YYTQV5rxBJCXCKbw0wdBzyohWcKqJZ2912DLyBQ=

    skip_cleanup: true
    file: package.tgz
    on:
      repo: starry-comet/comet-ioc
      tags: true
