language: node_js

node_js:
  - node
  - lts/boron
  - lts/argon

before_script:
  - yarn compile

before_deploy:
  - yarn pack --filename package.tgz

deploy:
  - provider: npm
    email: contact@florentin-dubois.fr
    api_key:
      secure: GUdEZPUVGLR+bzUe+TYQLswN9ukdz7PS8x5iA32uA17QhsP34FYs41XwQcobizh18VGK91iyQZJjjPF0mD6AD6aTzD8aEMEQs0FB1rfDotMPnZBiIlZOE/NIbdfQtcjk0vAl3/gTmOz6uK/30FnmE0KtDsfZHynGxaGvzvU7Qs7YgZO7qK5CLJn/j7imDr+9RafNhqHUCt8/5A+3zL5uRlh3FB4tliAuK77GvGjv0G1Dsc69NXck/e9O9DrfJDlJeDtBLuLxt915Q3jFKETNCSG0uuTNc5DwOn66l11YZxRAFFwX0rWtsxD19b+wMEU2aD9SSmMrShGn0LCOZxmfVmkXPLyuiC0vrghHYrfk19HONqAT5SiBGW6sGH8qihgjqqxxWwiNZEBqi+b+ztaiMEsblRtHmf91isVfmKyFQuYpn499m6s+cxHaRQUQZMK3Q8OLM2BJPfFnV0afNW0MkF8skUQbB6oq+eqjY5z0XKdBetvNR599fDC2bocSMsw92va879TsOFVxAcbmzhP3CwRmpP1AN17VZIWPiXI2s4N7dvODaLU/4RcnyvVwg4ehCydFlJeuX5/NQ/MKR7HX7R4bb7e2WvypNeky9ygfNX77g02qOVe8pJXhGCbAofdaZSBmhJGEib8WYEuN+K0hZxLssjhHu8LNmFSe2ly7GBY=

    skip_cleanup: true
    file: package.tgz
    on:
      tags: true
      repo: starry-comet/comet-ioc

  - provider: releases
    api_key:
      secure: N/bEH6SYwA3GDw76qlOLsh6VrQIaOx5bFcQa8FECdlJ/79GEDIH/NJwAlOnyU/z/nUoYTWXUSmtTkdGC1dZV6NUtZHeVrxECSSZhJ2XevDUueKiiIZIqbzl2zeogZoX2NVg3T81f8HysT/2oP9Xb3KBGZiMKj5rsqe4fSL5OrgL2lRXRzhLGtKYKinmrS83tTR14aSq8YktTbz3gTMPtoxdu9MCubKsZB+AZJruOaItXg4KX/4tNcBINJdDYZH2x+vrG219upaOCG8G6Fze35Ni3U/9d6+JPzvW7Ovf1pQlDLH/1E+NNrlXW9a4V4YK86Arb6VoEvIePq9tN8PoEPyqB0s0RyEBncjWqJ4RApkOIDwMxkuOlV3KZynHCI8G5DQwXSX//zfaNOKPefYvYUI/yHiM4dfsfAb3nvMsctyoSxRshyaB6mFYu44gjy3gLrhKJpKjdZQXg5SiLE/fNyE9gRvwOA9znpTtCm6E4lHn97t4Ozc1Z/8YkRWHEbFBKYOEpJJuT6NfyHK6BPoIRrZ6PkiiZGrQKzPXFiJYVJpUEPHa8DkW9xxcZwfNStQcQETjV0Vf4A7AC/lq8yLvvRgDCygob+Ws97z6WhWGTmFw+ip6dNB2ACJ9HhLj8KIfQ0MW2YYTQV5rxBJCXCKbw0wdBzyohWcKqJZ2912DLyBQ=

    skip_cleanup: true
    file: package.tgz
    on:
      repo: starry-comet/comet-ioc
      tags: true
